#DEFAULT
server:
  port: 8081
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    #static-path-pattern: /resources/**
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
#  profiles:
#    active: local
#    active: '@active.profile@'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:1318/webflux?serverTimezone=Asia/Seoul
    username: root
    password: 1318
  jpa:
    generate-ddl: true # @Entity 클래스를 찾아서 ddl을 생성하고 실행
    hibernate:
      ddl-auto: update # ddl 생성전략 validate|none
    show-sql: true # console에 sql 출력
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
config:
  upload-file-path: /home/standard/upload/

#---
##DEV
#spring:
#  profiles: dev
#  
#---
##PROD
#spring:
#  profiles: prod